### ISSUE TITLE
Create helpful commands

### ISSUE THREAD

**Issue by sdecandelario** [bcneng/bcneng.github.io#14]
As mentioned by Albert in the slack, is interesting to have some helpful commands, for example there a list:

- `?welcome`: Show the welcome message
- `?coc`: send the link of the [CoC](https://github.com/bcneng/bcneng.github.io/tree/master/coc)
- `?netiquette`: send the linkf of the [netiquette](https://github.com/bcneng/bcneng.github.io/tree/master/netiquette)

**Comment by gonzaloserrano** [comment]
This is now in the candebot repo.
