### ISSUE TITLE
Footer links open in new windows

### ISSUE THREAD

**Issue by sdecandelario** [bcneng/bcneng.github.io#21]
To kame things more comfortable is preferable to open external links in a new window/tab to make easier the navigation and the UX

**Comment by alombarte** [comment]
Indication for newcomers to Hugo:

The footer is part of the theme layout. To override this file it's needed to copy the file `themes/chunky-poster/layouts/partials/footer.html` into a new folder `layouts/partials/footer.html`

**Comment by GenisDiaz** [comment]
I've created a new pull request with this feature

**Comment by GenisDiaz** [comment]
The branch is merged with this feature.
